#Aastha Jain

#Excercise 1
#The difference betwen amount of power supplied and power demanded by each city.
diff_supplyDemand =vector("numeric",length = 20)

#data1 for power stations 
data1 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,1,1,1,9,6,6,1,3,2,8,11,8,18,6,4,13.60,12.00,5.60,0.76,0.65,1.12,5.53,5.53,7.35,0.78,1.09,0.78,1.45,7.74,0.95,
           0.16,0.16,0.14,0.02,0.01,0.02,0.17,0.17,0.12,0.02,0.02,0.02,0.02,0.02,0.01)

#data2 for daily_demand of 20 cities.
data2 <- c("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T",
           6.04,7.15,9.04,10.12,5.80,5.40,6.20,6.06,7.97,6.52,9.05,5.37,3.99,6.69,5.85,5.88,4.86,5.86,7.00,8.30)

#data3 for station i has committed x% energy to city j
data3<-c(30,20,15,0,0,21,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,20,0,0,41,0,15,0,7,0,0,0,9,0,0,0,0,
         0,10,0,0,0,0,10,0,25,5,10,0,10,0,10,0,0,10,10,0,0,0,0,80,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,
         0,20,0,0,0,0,0,10,0,0,15,0,10,0,0,0,10,10,10,0,15,0,10,10,0,0,15,0,0,7,8,0,0,0,0,9,6,20,
         0,15,0,3,6,9,0,15,0,11,7,0,10,0,12,0,0,14,0,0,0,0,13,7,5,6,8,4,5,5,5,5,8,4,10,5,5,4,4,2,
         2,3,3,3,3,2,2,4,4,5,5,10,4,8,5,5,5,5,4,8,6,5,7,10,10,10,10,0,0,0,0,10,0,15,0,0,15,0,0,0,
         0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,14,21,0,0,15,20,30,0,0,20,0,8,0,0,15,0,0,41,0,9,0,0,0,0,
         7,0,0,6,6,6,6,6,6,6,6,8,6,0,6,0,6,0,6,4,6,4,6,5,7,8,6,5,4,5,5,8,5,8,0,10,4,0,2,2,2,3,0,0,
         0,0,0,10,10,10,10,0,15,0,10,0,0,15,0,20,0,0,0)


power_stations = matrix(data1,nrow=15,ncol=4)

daily_demand = matrix(data2,nrow=2,ncol=20,byrow=TRUE)

station_city = matrix(data3,nrow=15,ncol=20,byrow=TRUE)

sampleValue <- function(success,failure){
  #On a random day ,generators are working or not are sampled randomly using 0 or 1
  # and probability of functional is equal to (1-p) for sample value 0 and is equal to p
  # for a value of 1.Generator cannot be half functional.
  return(sample(1:0,1,replace = TRUE,c(success,failure)))
}

daily_power <- function(){
 
  # Calculating Power generated by each station and distribution to cities :
  # 1.Create a vector of size n where n is number of generators for each station
  # 2.Sample values(0/1) in n using sample function(on basis of probability). On a random day,m out of n generators are working.(m<=n)
  # 3.Count(working_generators) number of working generators for each station.
  # 4.Multiply m * (c) where c is the capacity of producing  a uniform number of Megawatts per day.
  # Now
  # 5.Calculate amount of energy generated by station i(in previous step i.e on a random day)
  # has committed to city j(1-20). (eg 30% of 13.60MW)
  # 6.Summing up all the values that city j has received from different stations.
  # 7. The sum will be equal to Power supplied to city j on random day.
  #no of generators for each power station
  
  #The daily demand for each city on a random day.
  demand =vector("numeric",length=20)
  
  for(j in 1:ncol(daily_demand)) {
    demand[j] = daily_demand[2,j]
  }
  
  #total number of generators that are available per station.
  generators = vector(mode="numeric", length=15)
  
  # Each generator has a uniform probability pof not operating on a random day.
  prob_failure= vector(mode="numeric", length=15)
  
  for(i in 1:nrow(power_stations)){
    generators[i] =power_stations[i,2]
    prob_failure[i]=power_stations[i,4]
  } 
  
  #no of generators working for each power station on a random day.
  working_generators= vector(mode="numeric", length=15)
  
  for(i in 1:nrow(power_stations)){
    # Step 1
    x=vector(mode="numeric", length=(generators[i]))
    
    working_generators[i] =0
    
    for(j in 1:length(x)){
      # Step 2
      x[j] = sampleValue((1-prob_failure[i]),prob_failure[i])
      
      # Step 3
      if(x[j]==1) { working_generators[i]=working_generators[i]+1 }
    }
    
  }  
  #print(working_generators)
  
  #Step -4 Total power generated by each station i =(1,2,3...15) station_power =(m*c) where 
  # m is workig generators and c is Megawatt per generator produced by it.
  station_power = vector(mode="numeric", length=15)
  for(i in 1:length(station_power)){
    station_power[i] =working_generators[i]*power_stations[i,3]
  }
  #print(station_power)
  
  #Power supplied to each city on random day 
  power_distribution =matrix(nrow=15,ncol=20,byrow=TRUE)
  for(i in 1:nrow(station_city)){
    for(j in 1:ncol(station_city)){
      power_distribution[i,j]=station_power[i]*(station_city[i,j]/100)
    }
  }
  #print(power_distribution)
  
  #Step 5 Sum up the columns's of power_distribution to get total power supplied to city j (1=< j<= 20)
  supply = vector(mode="numeric", length=20)
  supply = colSums(power_distribution)
  
  diff_supplyDemand <<- supply- as.numeric(demand)
  
  #Data frame that print column1 as demand for station i=1,2,3...15 
  #                      column2 as power supplied
  #                      column3 as difference between power demanded and power supplied.
  df=data.frame(demand,supply,diff_supplyDemand)
  print(df)
  
} 
#solution Excercise 1
#    demand  supply diff_supplyDemand
#1    6.04 10.5327            4.4927
#2    7.15 10.2328            3.0828
#3    9.04 11.8461            2.8061
#4   10.12 11.4582            1.3382
#5     5.8  8.5673            2.7673
#6     5.4  8.4815            3.0815
#7     6.2  8.5403            2.3403
#8    6.06 11.3211            5.2611
#9    7.97  9.2429            1.2729
#10   6.52  9.4478            2.9278
#11   9.05  8.4020           -0.6480
#12   5.37  5.8661            0.4961
#13   3.99  6.1886            2.1986
#14   6.69  6.9256            0.2356
#15   5.85  6.0580            0.2080
#16   5.88  6.5388            0.6588
#17   4.86  5.2318            0.3718
#18   5.86  6.2981            0.4381
#19      7  7.0362            0.0362
#20    8.3  8.7271            0.4271
  
#Excercise 2
#If the demand exceeds the supply then day is called as blackout day.If more than on part of county
#is experiencing temporarily lossof a power on random day .We say it blackOut for that random day.
# BlackOut is denoted by 1 and No blackout for 15 stations means a valued denoted by 0.
failure <- function(){
    #print(diff_supplyDemand)
  
    for(i in 1:length(diff_supplyDemand)){
      if(diff_supplyDemand[i] <= 0){
        blackOut=1
        break
        }
      else{
        blackOut=0
      }
    }
  return(blackOut)
}
#Solution Excercise 2 Part 1 (Above Data,blackOut =1)
# 1

#n: number of samples, delta: the degree of confidence sought (e.g. delta = 0.95),
#sample: function used to generate a single sample
imc = function(n,delta,f)
{
  sum = 0
  sumsq = 0
  x = 0
  total_blackOuts = 0
  
  for(i in 1:(n))
  {
    daily_power()
    x = f()
    sum = sum + x
    sumsq = sumsq + x*x
    if(x ==1){
      total_blackOuts= total_blackOuts+1
    }
  }
  
 
  
  pf=(total_blackOuts)/(n)
  lambda=sum/n
  sigmasq = (sumsq + (lambda*lambda*n))/(n-1)
  se = sqrt(sigmasq/n)
  re = se/lambda
  qdelta = qnorm((1+delta)/2)
  ci_left = lambda-qdelta*se
  ci_right = lambda+qdelta*se
  mttf=(1/pf)-1
  cat("Probability of failure day:",pf,"\n")
  #cat("Number of samples:",n,"\n")
  cat("Sample mean:",lambda,"\n")
  cat("Sample variance:",sigmasq,"\n")
  cat("Standard error:",se,"\n")
  cat(delta,"-confidencse interval: [",ci_left,",",ci_right,"]\n",sep="")
  cat("Mean time between failure :",(1/pf)-1,"\n")
  return(mttf)
}

#Solution to Excercise 2 Part 2(50,000 samples being used)
#imc(50000,0.90,failure)
#Probability of failure day: 0.61252 
#Sample mean: 0.61252 
#Sample variance: 0.9877205 
#Standard error: 0.004444593 
#0.9-confidencse interval: [0.6052093,0.6198307]
#Mean time between failure : 0.6325998 


imc2 = function(n,delta,f,a,b)
{
  sum = 0
  sumsq = 0
  x = 0
  total_blackOuts = 0
  
  for(i in 1:(n))
  {
    daily_power()
    x = f(a,b)
    sum = sum + x
    sumsq = sumsq + x*x
    if(x ==1){
      total_blackOuts= total_blackOuts+1
    }
  }
  
  pf=(total_blackOuts)/(n)
  lambda=sum/n
  sigmasq = (sumsq + (lambda*lambda*n))/(n-1)
  se = sqrt(sigmasq/n)
  re = se/lambda
  qdelta = qnorm((1+delta)/2)
  ci_left = lambda-qdelta*se
  ci_right = lambda+qdelta*se
  mttf=(1/pf)-1
  cat("Probability of failure day:",pf,"\n")
  #cat("Number of samples:",n,"\n")
  cat("Sample mean:",lambda,"\n")
  cat("Sample variance:",sigmasq,"\n")
  cat("Standard error:",se,"\n")
  cat(delta,"-confidencse interval: [",ci_left,",",ci_right,"]\n",sep="")
  cat("Mean time between failure :",(1/pf)-1,"\n")
  return(mttf)
}

 #Excercise 3
 #accept station s and new probability p
 failure2 <- function(s,q_new){
  
   #calculating the station s with new failure q_new probability.
   
   demand =vector("numeric",length=20)
   for(j in 1:ncol(daily_demand)) {
     demand[j] = daily_demand[2,j]
   }
  
   #Setting station s with the new proabibility that the user enters
   for(i in 1:nrow(power_stations)){
     power_stations[s,4]=q_new 
   }
   
   
   #print(power_stations[,4])
   generators = vector(mode="numeric", length=15)
   prob_failure= vector(mode="numeric", length=15)
   for(i in 1:nrow(power_stations)){
     generators[i] =power_stations[i,2]
     prob_failure[i]=power_stations[i,4]
   } 
   #print(generators)
   
   #no of generators working for each power station on a random day.
   working_generators= vector(mode="numeric", length=15)
   
   for(i in 1:nrow(power_stations)){
     # Step 1
     x=vector(mode="numeric", length=(generators[i]))
     
     working_generators[i] =0
     
     for(j in 1:length(x)){
       # Step 2
       x[j] = sampleValue((1-prob_failure[i]),prob_failure[i])
       
       #cat(x[j])
       
       # Step 3
       if(x[j]==1) { working_generators[i]=working_generators[i]+1 }
     }
     
   }  
   #print(working_generators)
   
   #Step -4 Total power generated by each station (1 -15) =(m*c)
   station_power = vector(mode="numeric", length=15)
   for(i in 1:length(station_power)){
     station_power[i] =working_generators[i]*power_stations[i,3]
   }
   #print(station_power)
   
   #Power supplied to each city on random day 
   power_distribution =matrix(nrow=15,ncol=20,byrow=TRUE)
   for(i in 1:nrow(station_city)){
     for(j in 1:ncol(station_city)){
       power_distribution[i,j]=station_power[i]*(station_city[i,j]/100)
     }
   }
   #print(power_distribution)
   
   #Step 5 Sum up the columns's of power_distribution to get total power supplied to city j (1=< j<= 20)
   supply = vector(mode="numeric", length=20)
   supply = colSums(power_distribution)
   
   #print(supply) #required
   
   
   diff_supplyDemand <<- supply- as.numeric(demand)
   #print(diff_supplyDemand)
   
   #Data frame that print column1 as demand for station i=1,2,3...15 
   #                      column2 as power supplied
   #                      column3 as difference between power demanded and power supplied.
   df=data.frame(demand,supply,diff_supplyDemand)
   print(df)
   
   for(i in 1:length(diff_supplyDemand)){
     if(diff_supplyDemand[i] <= 0){
       blackOut=1
       break
     }
     else{
       blackOut=0
     }
   }
   return(blackOut)

 }
#Solution to Excercise 3
 " Run -->    failure2(12,0.01)
   
 demand  supply diff_supplyDemand
 1    6.04 10.7531            4.7131
 2    7.15 10.6066            3.4566
 3    9.04 12.1685            3.1285
 4   10.12 11.6272            1.5072
 5     5.8  9.0271            3.2271
 6     5.4  8.6406            3.2406
 7     6.2  9.0183            2.8183
 8    6.06 11.7991            5.7391
 9    7.97 10.2422            2.2722
 10   6.52  9.5968            3.0768
 11   9.05  9.3880            0.3380
 12   5.37  5.6806            0.3106
 13   3.99  7.0536            3.0636
 14   6.69  7.3262            0.6362
 15   5.85  6.1035            0.2535
 16   5.88  6.6992            0.8192
 17   4.86  5.6400            0.7800
 18   5.86  6.7833            0.9233
 19      7  7.3020            0.3020
 20    8.3  9.0757            0.7757
 [1] 0
"

 
 #Excercise 4 (using 50,000 samples)
 

consortium_report <- function(){
  #upgrading each station by reducing the probability by half of origional probability
  p=vector(mode="numeric",length=15)
  mttf_original = vector(mode="numeric",length=15)
  mttf_upgraded = vector(mode="numeric",length=15)
  for(i in 1:15){
    p = power_stations[ ,4]
    mttf_original[i]=imc2(100,0.90,failure2,i,p[i])
    
    mttf_upgraded[i]=imc2(100,0.90,failure2,i,p[i]/2)
   
    
  }
  for(i in 1:15){
    cat(" ",mttf_upgraded[i],mttf_original[i])
  #if(mttf_upgraded[i]-mttf_original[i] >= 4){
  #  cat("station  number: ",power_stations[i,1],"\n")
  #  cat("mean time between failure is: ",mttf_upgraded[i],"\n")
  #}
    
  }
  
 
}