sampleValue <- function(success,failure){
  #On a random day ,generators are working or not are sampled randomly using 0 or 1
  # and probability of functional is equal to 0 for sample value 0 and is equal to 1
  # for a value of 1.Generator cannot be half functional.
  return(sample(1:0,1,replace = TRUE,c(success,failure)))
}


daily_power <- function(){
  
  data1 <- c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,1,1,1,9,6,6,1,3,2,8,11,8,18,6,4,
            13.60,12.00,5.60,0.76,0.65,1.12,5.53,5.53,7.35,0.78,1.09,0.78,1.45,7.74,0.95,
            0.16,0.16,0.14,0.02,0.01,0.02,0.17,0.17,0.12,0.02,0.02,0.02,0.02,0.02,0.01)
  
  power_stations =matrix(data1,nrow=15,ncol=4)
  
  data2 <- c("A","B","C","D","E","F","G","H","I","J","K","L","M","N","O","P","Q","R","S","T",
             6.04,7.15,9.04,10.12,5.80,5.40,6.20,6.06,7.97,6.52,9.05,5.37,3.99,6.69,5.85,
             5.88,4.86,5.86,7.00,8.30)
  daily_demand =matrix(data2,nrow=2,ncol=20,byrow=TRUE)
  
  data3<-c(30,20,15,0,0,21,14,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,8,0,20,0,0,41,0,15,0,7,0,0,0,9,0,0,0,0,
           0,10,0,0,0,0,10,0,25,5,10,0,10,0,10,0,0,10,10,0,0,0,0,80,0,0,0,0,0,0,0,0,0,0,0,20,0,0,0,
           0,20,0,0,0,0,0,10,0,0,15,0,10,0,0,0,10,10,10,0,15,0,10,10,0,0,15,0,0,7,8,0,0,0,0,9,6,20,
           0,15,0,3,6,9,0,15,0,11,7,0,10,0,12,0,0,14,0,0,0,0,13,7,5,6,8,4,5,5,5,5,8,4,10,5,5,4,4,2,
           2,3,3,3,3,2,2,4,4,5,5,10,4,8,5,5,5,5,4,8,6,5,7,10,10,10,10,0,0,0,0,10,0,15,0,0,15,0,0,0,
           0,0,20,0,0,0,0,0,0,0,0,0,0,0,0,0,14,21,0,0,15,20,30,0,0,20,0,8,0,0,15,0,0,41,0,9,0,0,0,0,
           7,0,0,6,6,6,6,6,6,6,6,8,6,0,6,0,6,0,6,4,6,4,6,5,7,8,6,5,4,5,5,8,5,0,0,10,0,0,0,0,0,0,0,0,
           0,0,0,10,10,10,10,0,15,0,10,0,0,15,0,20,0,0,0)
  
  station_city =matrix(data3,nrow=15,ncol=20,byrow=TRUE)
  
  #print(power_stations)
  #print(daily_demand)
  #print(station_city)
  
  print("(i)The daily demand for each city :")
  demand =vector("numeric",length=20)
    for(j in 1:ncol(daily_demand)) {
       #cat(daily_demand[1,j]," require ",daily_demand[2,j]," Megawatts\n")
       demand[j]= daily_demand[2,j]
    }
  print(as.numeric(demand))
  # Calculating Power generated by each station and distribution to cities :
  # 1.Create a vector of size n where n is number of generators for each station
  # 2.Sample values(0/1) in n using sample function(on basis of probability). On a random day,m out of n generators are working.(m<=n)
  # 3.Count(working_generators) number of working generators for each station.
  # 4.Multiply m * (c) where c is the capacity of producing  a uniform number of Megawatts per day.
  # Now
  # 5.Calculate amount of energy generated by station i(in previous step i.e on a random day)
  # has committed to city j(1-20). (eg 30% of 13.60MW)
  # 6.Summing up all the values that city j has received from different stations.
  # 7. The sum will be equal to Power supplied to city j on random day.
  #no of generators for each power station
  generators = vector(mode="numeric", length=15)
  prob_failure= vector(mode="numeric", length=15)
  for(i in 1:nrow(power_stations)){
    generators[i] =power_stations[i,2]
    prob_failure[i]=power_stations[i,4]
  } 
  #print(generators)
  
  #no of generators working for each power station on a random day.
  working_generators= vector(mode="numeric", length=15)
  
  for(i in 1:nrow(power_stations)){
    # Step 1
    x=vector(mode="numeric", length=(generators[i]))
    
    working_generators[i] =0
    
    for(j in 1:length(x)){
       # Step 2
       x[j] = sampleValue((1-prob_failure[i]),prob_failure[i])
    
       #cat("")
       #cat(x[j])
    
       # Step 3
       if(x[j]==1) { working_generators[i]=working_generators[i]+1 }
    }
   
  }  
 #print(working_generators)
  
  #Step -4 Total power generated by each station (1 -15) =(m*c)
  station_power = vector(mode="numeric", length=15)
  for(i in 1:length(station_power)){
    station_power[i] =working_generators[i]*power_stations[i,3]
  }
  #print(station_power)

  print("(ii) Power supplied to each city on random day :")
  power_distribution =matrix(nrow=15,ncol=20,byrow=TRUE)
  for(i in 1:nrow(station_city)){
    for(j in 1:ncol(station_city)){
      power_distribution[i,j]=station_power[i]*(station_city[i,j]/100)
    }
  }
  #print(power_distribution)
  
  #Step 5 Sum up the columns's of power_distribution to get total power supplied to city j (1=< j<= 20)
  supply = vector(mode="numeric", length=20)
  supply = colSums(power_distribution)
 
  print(supply) #required
  
  print("(iii) difference between supply and demand :")
  diff_supplyDemand=vector("numeric",length = 20)
  diff_supplyDemand = supply- as.numeric(demand)
  print(diff_supplyDemand)
}